packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  prettier: ^3.4.2

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  esbuild: true
  '@scarf/scarf': false
  unrs-resolver: false
